//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_progect
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondCourseSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecondCourseSet()
        {
            this.ProductTraking = new HashSet<ProductTraking>();
        }
    
        public int Id { get; set; }
        public string Dish { get; set; }
        public string Сomposition { get; set; }
        public string Prise { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTraking> ProductTraking { get; set; }
    }
}
